util: add fiemap fallback for errno ENOTTY
On WSL-1, genimage fails with (see [1] for details):

  ERROR: hdimage(sdcard.img): fiemap .../boot.vfat: 25 Inappropriate ioctl for device

This is because WSL-1 is a limited Linux emulation layer, where the fiemap
ioctl incorrectly returns ENOTTY instead of the expected EOPNOTSUPP.

[1] https://bugs.busybox.net/show_bug.cgi?id=13146

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
---
Changes v1 -> v2:
  - improved commit message (according to suggestion by Yann E. MORIN)